# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
title: LRodrigo WebSite
tagline: LRodrigo WebSite
email: luisrodrigoog@gmail.com
description: >
  Site pessoal de LRodrigo com meu material de aula e dias sobre o mundo Linux e Python.
baseurl: "/hp"
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://luisrodrigoog.github.io" 

twitter_username: luisrodrigoog 
github_username:  luisrodrigoog
gh_sponsor: luisrodrigoog

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

remote_theme: chrisrhymes/bulma-clean-theme

#permalink: pretty
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

paginate: 5
paginate_path: "/blog/page:num"

plugins:
- github-pages
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- kramdown
- rouge



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: [_pages, _dicas, _cursos, download, blog]

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "LRodrigo"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

#footer_menu: example_footer_menu

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false


