# Site Settings
title: LRodrigo WebSite
tagline: LRodrigo WebSite
email: luisrodrigoog@gmail.com
description: >
  Site pessoal de LRodrigo com meu material de aula e dias sobre o mundo Linux e Python.
baseurl: "/hp"
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://luisrodrigoog.github.io" 

twitter_username: luisrodrigoog 
github_username:  luisrodrigoog
gh_sponsor: luisrodrigoog

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed
remote_theme: chrisrhymes/bulma-clean-theme

#permalink: pretty
#permalink: /:categories/:year/:month/:day/:title/
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

paginate: 5
paginate_path: "/blog/page:num"

disqus:
    shortname: luisrodrigoog

plugins:
- github-pages
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- kramdown
- rouge

# Google Analytics
google_analytics: UA-52297903-2



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: [_pages, _dicas, _cursos, _includes,  download, blog, img]

#livereload: true

#sass:
#  style: compressed
#  source_dir: _sass

defaults:
#  -
#    scope:
#      path: ""
#      type: "pages"
#    values:
#      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "LRodrigo"
      layout: post
      image: /hp/img/topo-001.jpg
      hero_image: /hp/img/topo-001.jpg
      show_sidebar: true

#markdown: kramdown
#highlighter: rouge

#footer_menu: example_footer_menu

#collections:
#  products:
#    output: true
#    layout: product
#    image: https://via.placeholder.com/800x600
#    show_sidebar: false
